EP-7433: Fix handover and metadata documentation
Ensembl/ensembl-prodinf-tools pull request #16
Opened 2021-11-18 16:06 UTC by luca-drf

2021-11-18 16:27 UTC, marcoooo commented on requirements.txt
> +ensembl-prodinf-core@git+https://github.com/Ensembl/ensembl-prodinf-core.git@1.3.1
```suggestion
ensembl-prodinf-core~=2.0.0
```

2021-11-18 16:39 UTC, marcoooo requested changes
Just the dependency to code to update.

2021-11-18 17:19 UTC, luca-drf commented
> Just the dependency to code to update.

I forgot we had it on version 2.0.0 on PyPI, thanks!

2021-11-19 09:52 UTC, marcoooo approved these changes

2021-11-19 12:42 UTC, merged